# Generated by Django 4.2.3 on 2023-08-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250, verbose_name='Изображение')),
                ('name', models.CharField(max_length=20, verbose_name='Название напитка')),
                ('price', models.CharField(max_length=5, verbose_name='price')),
                ('description', models.TextField(verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Комбо',
                'verbose_name_plural': 'Комбо',
            },
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250, verbose_name='Изображение')),
                ('name', models.CharField(max_length=20, verbose_name='Название напитка')),
                ('price', models.CharField(max_length=5, verbose_name='price')),
                ('description', models.TextField(verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Десерт',
                'verbose_name_plural': 'Десерты',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250, verbose_name='Изображение')),
                ('name', models.CharField(max_length=20, verbose_name='Название напитка')),
                ('price', models.CharField(max_length=5, verbose_name='price')),
                ('description', models.TextField(verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250, verbose_name='Изображение')),
                ('name', models.CharField(max_length=20, verbose_name='Название напитка')),
                ('price', models.CharField(max_length=5, verbose_name='price')),
                ('description', models.TextField(verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Ролл',
                'verbose_name_plural': 'Роллы',
            },
        ),
    ]
