# Generated by Django 4.2.3 on 2023-08-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_combo_dessert_drink_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250, verbose_name='Изображение')),
                ('name', models.CharField(max_length=20, verbose_name='Название напитка')),
                ('price', models.CharField(max_length=5, verbose_name='price')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Десерт',
                'verbose_name_plural': 'Десерты',
            },
        ),
    ]
